### PR TITLE
✨ add coordinates to ImagineOutput

### PR DESCRIPTION
**Pull request by garak**
See https://github.com/p-chess/chess/pull/37#issuecomment-806492060

### CODE REVIEW

**Comment by garak** [comment]
The failed test is random... sometimes it fails, sometimes it passes.
I guess we should change it to something more robust

**Comment by akondas** [comment]
Nice, can you add image with coordinates to readme?

**Comment by garak** [comment]
> Nice, can you add image with coordinates to readme?

Well, currently is not really a great image: I just created some images for letters/numbers, but I'm not really good with images...
This is the current result:

board

**Comment by garak** [comment]
And this is a different try, made with uncommitted code (using a font to generate coordinates, instead of relying on images).
Problem with such approach is in calculating the right size and position of font, given the board size

board2

**Comment by akondas** [comment]
Both are pretty good, if you want you can add them to the repo later. Thanks for the whole thing :beers:

**Review by akondas — APPROVED** [review]

**Pull request merged**
