### PR TITLE
♻️ refactors History

### PR DESCRIPTION
**Pull request by garak**
Yet another array removed and replaced with a real object.

### CODE REVIEW

**Review by akondas — APPROVED** [review]

**Comment by akondas** [comment]
Thanks :+1:

**Comment by garak** [comment]
Tag 0.2.0?

**Comment by garak** [comment]
> Yup, if you want, you can always create it too wink

Are you sure? I just tried this morning, but it failed...

**Comment by akondas** [comment]
Ok, corrected.

**Pull request merged**
