### PR TITLE
⬆️ allow php8

### PR DESCRIPTION
**Pull request by garak**
Also, upgrade some other deps and improve some minor parts of code

### CODE REVIEW

**Comment by garak** [comment]
Maybe we can consider the option to migrate CI to github actions?

**Comment by akondas** [comment]
> Maybe we can consider the option to migrate CI to github actions?

Why? Is there something wrong with the current CI?

From what I can see composer lock has not been updated:
```
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
```

**Comment by garak** [comment]
Yes, I see that buddy should be updated to get it working with PHP 8.
I'm not really familiar with it, github actions is just something "more standard"

**Comment by akondas** [comment]
Added build for version 8. 

You can implement actions in github if it gives you something more. For my part, I would like to keep the build in Buddy. If it often causes problems, we can turn it off.

**Comment by akondas** [comment]
If you have a different opinion on this matter, I am also open to further conversation. I am more interested in a consensus than a compromise :wink:

**Comment by garak** [comment]
> If you have a different opinion on this matter, I am also open to further conversation. I am more interested in a consensus than a compromise wink

Well, I just see buddy as "exotic", never seen on other projects. Github actions, on the other hand, is becoming a new de facto standard, being Travis' popularity decreasing.
But I think that having a working CI is more important than CI itself.

**Review by akondas — APPROVED** [review]
Nice, thanks :+1:

**Pull request merged**
