### PR TITLE
✨ add HtmlOutput

### PR DESCRIPTION
**Pull request by garak**
Yet another output class 😉
This one is a bit more elaborate since you need some additional information to build a functional HTML board.
But I think it's totally worth it: it's a base to build an online Chess game

### CODE REVIEW

**Comment by akondas** [comment]
I'm not exactly a fan of mixing direct php and html. I would see such integration more using, for example, Twig :thinking:  ... but on the other hand it's just chess, so I guess I'm merge this :wink:

**Review by akondas — APPROVED** [review]

**Comment by garak** [comment]
Thank you @akondas 
I was thinking about creating a chess-bundle, to integrate this project in Symfony. Do you mind adding a repo in p-chess?

**Comment by akondas** [comment]
You can add such a repository, as a member of the organization you have the appropriate rights to do so :wink:

**Comment by garak** [comment]
@akondas I just did it.
I need a couple of actions on your side, please:
1) submit package to packagist
2) enable buddy CI

**Comment by akondas** [comment]
Done. I also added you to the packagist mainteners. As for the Buddy, I did it too, but we can consider Github actions in the future, because it will be easier for future projects - will not require any interaction on my part :wink:

**Pull request merged**
