### PR TITLE
🚧 make some Piece properties private

### PR DESCRIPTION
**Pull request by garak**
This is a Work in Progress I extracted before sending from previous PR.
As you can see, I only changed two Piece properties to be private (using getters and one setter).

Anyway, despite this simple change, two tests are failing and I can't spot the reason...

### CODE REVIEW

**Comment by akondas** [comment]
```
There were 2 failures:
1) PChess\Chess\Test\PerftTest::test2
Failed asserting that 2039 is identical to 1901.
/buddy/chess/tests/PerftTest.php:26
2) PChess\Chess\Test\PerftTest::test6
Failed asserting that 2079 is identical to 2109.
/buddy/chess/tests/PerftTest.php:62
FAILURES!
```

**Comment by garak** [comment]
Exactly. Can you help me to find what's wrong?

**Comment by garak** [comment]
I tried some permutations and found a single point of failure in `$type` property (in `Piece` class).
If you change the code in this PR to make it public again, all tests are green. If you switch to private again, two tests failed.

I'm really scratching my head, since this doesn't make sense to me. I can't find any part inside codebase when such property is tried to be accessed directly.

**Comment by garak** [comment]
I found a possible smell in PerftTest class: I think that we should not call `perft()` method on the same `Chess` object without resetting.
So, for example, the following test:
```php
public function test2(): void
{
    $chess = new ChessPublicator('r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1');
    $this->assertSame($chess->perft(1), 48);
    $this->assertSame($chess->perft(2), 2039);
}
```
should be instead
```php
public function test2(): void
{
    $chess = new ChessPublicator('r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1');
    $this->assertSame($chess->perft(1), 48);
    $chess->reset();
    $this->assertSame($chess->perft(2), 400);
}
```
With such change, tests are passing in both cases (`$type` public and/or private)

**Comment by akondas** [comment]
Just why it changed after the changes in this pull request?

**Comment by garak** [comment]
> Just why it changed after the changes in this pull request?

I'm not sure to understand your question...

**Comment by garak** [comment]
I'm closing this, since it was only a way to share my problem.
Will opening a new PR

**Pull request closed without merging**
